controllers:
    resource:
        path: ../src/Presentation/Controller/
        namespace: App\Presentation\Controller
    type: attribute

main:
    resource: 'routes/main.yaml'
    name_prefix: 'main_'
