parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude:
            - '../src/{Domain,Presentation}'
            - '../src/Kernel.php'

    App\Presentation\Controller\:
        resource: '../src/Presentation/Controller'
        tags: [ 'controller.service_arguments' ]
